config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  # Topページ遷移
  root to: 'movies#index'

  resources :questions do
  resources :solutions
  end
  resources :aws
  resources :movies
  resources :lines
  
  resources :texts do
    collection do
      get 'search'
    end
  end

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  require 'csv'
end

app/models/aws_text.rb
class AwsText < ApplicationRecord
  validates :title , presence: true
  validates :content , presence: true

end

app/models/line_text.rb
class LineText < ApplicationRecord
  validates :genre , presence: true
  validates :title , presence: true
  validates :content , presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :title , presence: true
  validates :url, presence: true
  validates :genre, presence: true  
end

app/models/question.rb
class Question < ApplicationRecord
  validates :title, presence: { message: "は空欄にできません" }
  validates :detail, presence: { message: "は空欄にできません" }
  has_many :solutions
end

app/models/solution.rb
class Solution < ApplicationRecord
    validates :detail , presence: true
    belongs_to :question
end

app/models/text.rb
class Text < ApplicationRecord
    validates :genre, presence: true
    validates :title, presence: true
    validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/aws_controller.rb
class AwsController < ApplicationController

  def index
    @awsTexts = AwsText.all
  end

  def show
    @awsText = AwsText.find_by(id: params[:id])
  end
  
  
end

app/controllers/lines_controller.rb
class LinesController < ApplicationController
  def index
    @lineTexts = LineText.all
  end

  def show
    @lineText = LineText.find_by(id: params[:id])
  end
  
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
 def index

   movie_genre = ["Basic","Git","Ruby","Ruby on Rails"]
   # PER = 10

   case params[:genre]
   when "Talk","Live","Php","Writing","Marketing","Movie"
      @movies = Movie.where(genre: params[:genre]).page(params[:page]).per(10)
   else
      @movies = Movie.where(genre: movie_genre).page(params[:page]).per(10)
   end
   
 end
end  

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @question = Question.new
    @questions = Question.all.order(id: "DESC")
  end

  def show
    @question = Question.find_by(id: params[:id])
    @solutions = @question.solutions
    @solution = Solution.new
    @question.increment!(:reviews_count, 1)
  end

  def create
    @question = Question.new(question_params)
    if @question.save
      redirect_to action: :index
      flash[:notice] = "登録に成功しました"
    else
      @questions = Question.all.order(created_at: :desc)
      render :index
    end
  end

  private
    def question_params
      params.require(:question).permit(:title, :detail)
    end
end

app/controllers/solutions_controller.rb
class SolutionsController < ApplicationController

 def create
    @question = Question.find(params[:question_id])
    @solution = @question.solutions.build(solution_params)
  
    if @solution.save
        redirect_to @question, notice: "質問を投稿しました"
    else
      flash.now[:alert] = "エラーが発生しました"
       @solutions = @question.solutions
       render "questions/show"
    end
  end

  private
    def solution_params
      params.require(:solution).permit(:detail)
    end
end

app/controllers/texts_controller.rb
class TextsController < ApplicationController
    def index
        @texts = Text.all
    end

    def show
        @text = Text.find(params[:id])
    end

    
end

app/helpers/application_helper.rb
module ApplicationHelper
  require "redcarpet"
  require "coderay"

  class HTMLwithCoderay < Redcarpet::Render::HTML
      def block_code(code, language)
          language = language.split(':')[0] if language.present?

          case language.to_s
          when 'rb'
              lang = :ruby
          when 'yml'
              lang = :yaml
          when 'css'
              lang = :css
          when 'html'
              lang = :html
          when ''
              lang = :md
          else
              lang = language
          end

          CodeRay.scan(code, lang).div
      end
  end

  def markdown(text)
      html_render = HTMLwithCoderay.new(
        filter_html: true,
        hard_wrap: true,
        link_attributes: { rel: 'nofollow', target: "_blank" }
      )
      options = {
          autolink: true,
          space_after_headers: true,
          no_intra_emphasis: true,
          fenced_code_blocks: true,
          tables: true,
          hard_wrap: true,
          xhtml: true,
          lax_html_blocks: true,
          strikethrough: true
      }
      markdown = Redcarpet::Markdown.new(html_render, options)
      markdown.render(text)
  end
  def background_color_class
    controller_name == "lines" ? "bg-success" : "bg-primary"
  end

  def wrap_style
    (controller_name == "texts" && action_name == "index") ? "rails_text_wrap" : "default_wrap"
  end



end

app/views/aws/index.html.erb
<div class="container">
  <div class="contents">
    <div class="text-center">
      <div class="aws-title">
      <h2>AWS講座</h2>
      </div>
    </div>
    <p>注意！！！：AWSのEC2やRDSは有料サービスとなります。無駄な料金を請求されないためにも、不要なインスタンスは停止・削除をしてください。</p>
    <div class="table-container">
      <table class="table table-striped">
        <thead class="aws-table-head text-white">
          <tr>
            <th class="w-1">No.</th>
            <th class="w-5">内容</th>
          </tr>
          <tbody>
          <% @awsTexts.each.with_index(1) do |aws, i| %>
            <tr>
              <td><%= i %></td>
              <td><%= link_to("#{aws.title}", "/aws/#{aws.id}", target: :_blank) %></td>
            </tr>
            <% end %>
          </tbody>
        </thead>
      </table>
    </div>
  </div>
</div>

app/views/aws/show.html.erb
  <section id="aws-contents">
  <h2><%= @awsText.title %></h2>
  <%= markdown(@awsText.content).html_safe %>
  </section>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>">
      <%= message %>
    </div>
<% end %>

app/views/layouts/_footer.html.erb
<div class="fixed-bottom <%= background_color_class %>">    
    <footer class="footer mt-auto py-3 text-center">
            <div class="container">
                <a class="text-white" target="_blank" href="http://utina.yoshitokamizato.com/">ブログ</a>
                <a class="text-white" target="_blank" href="https://www.youtube.com/channel/UCwrDvYey9uKGBeh_l5IF-ag">Youtube</a>
            </div>
    </footer>
</div>

app/views/layouts/_navbar.html.erb
<div class="fixed-top <%= background_color_class %>" >
    <nav class="navbar navbar-expand-xl navbar-dark mx-auto">
        <a class="navbar-brand" href="/">Gyakuten</a>
        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#Navbar" aria-controls="Navbar" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
            <div class="collapse navbar-collapse" id="Navbar">
                <ul class="navbar-nav">
                    <li class="nav-item active dropdown">
                    <a class="nav-link dropdown-toggle" href="/" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Rails
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <%= link_to "動画教材", movies_path, class: "nav-item nav-link active text-primary" %>
                        <%= link_to "テキスト教材", texts_path, class: "nav-item nav-link active text-primary" %>
                        <%= link_to "ライブコーディング", movies_path(genre: "Live"), class: "nav-item nav-link active text-primary" %>
                        <%= link_to "質問集", questions_path, class: "nav-item nav-link active text-primary" %>
                    </div>
                    </li>
                    <li class="nav-item">
                        <%= link_to "AWS講座", aws_path, class: "nav-item nav-link active" %>
                    </li>
                    <li class="nav-item">
                        <%= link_to "PHP講座",  movies_path(genre: "Php"), class: "nav-item nav-link active" %>
                    </li>
                    <li class="nav-item">
                        <%= link_to "対談",  movies_path(genre: "Talk"), class: "nav-item nav-link active" %>
                    </li>
                    <li class="nav-item">
                        <%= link_to "情報発信",  movies_path(genre: "Marketing"), class: "nav-item nav-link active" %>
                    </li>
                    <li class="nav-item">
                        <%= link_to "動画編集講座",  movies_path(genre: "Movie"), class: "nav-item nav-link active" %>
                    </li>
                    <li class="nav-item">
                        <%= link_to "ライティング講座",  movies_path(genre: "Writing"), class: "nav-item nav-link active" %>
                    </li>
                    <li class="nav-item">
                        <%= link_to "LINE@",  lines_path, class: "nav-item nav-link active" %>
                    </li>
                    <li class="nav-item">
                    <a class="nav-item nav-link active" href="#">新規登録</a>
                    </li>
                    <% if user_signed_in? %>
                    <li class="nav-item">
                        <%= link_to "ログアウト",  destroy_user_session_path, method: :delete, class: "nav-item nav-link active" %>
                    </li>
                    <% else %>
                    <li class="nav-item">
                        <%= link_to "ログイン",  new_user_session_path, method: :delete, class: "nav-item nav-link active" %>
                    </li>
                    <% end %>
                </ul>
        </div>
    </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GyakutenCloneGroup</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <header>
        <%= render 'layouts/navbar' %>
      </header>
        <%= render 'layouts/flash_messages' %>
        <main class ="<%= wrap_style %>">
          <%= yield %>
        </main>
        <%= render 'layouts/footer' %>
  </body>
</html>

app/views/lines/index.html.erb
<div class="container">
  <div class="contents">
    <div class="text-center">
      <h2>LINE@</h2>
    </div>
    <div class="table-container">
      <table class="table table-striped">
        <thead class="bg-success text-white">
          <tr>
            <th class="w-1">No.</th>
            <th class="w-2">ジャンル</th>
            <th class="w-5">内容</th>
          </tr>
          <tbody>
          <% @lineTexts.each.with_index(1) do |line, i| %>
            <tr>
              <td><%= i %></td>
              <td><%= line.genre %></td>
              <td><%= link_to("#{line.title}", "/lines/#{line.id}", target: :_blank) %></td>
            </tr>
            <% end %>
          </tbody>
        </thead>
      </table>
    </div>
  </div>
</div>

app/views/lines/show.html.erb
<section id="line-contents">
  <%= markdown(@lineText.content).html_safe %>
</section>

app/views/movies/index.html.erb
<div class="text-center">
  <div class="col-xs-12">
    <div class="movie-title">
      <% @movies.each.with_index(1) do |movie, i| %>
        <div class="mt-5">
          <% case movie.genre %>
          <% when "Basic","Git","Ruby","Ruby on Rails","Marketing" %>
          <p><%= "Lv.#{(@movies.current_page - 1) * 10 + i}: #{movie.title}" %></p>

          <% else %>
          <p><%= movie.title %></p>

          <% end %>
        </div>
        <iframe width="560" height="315" src="<%= movie.url %>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      <% end %>
    </div>
    <%= paginate @movies %>
  </div>
</div>

app/views/questions/index.html.erb
<div class="container">
  <div class="questions">
    <div class="text-left">
      <h2>新規投稿</h2>
      <%= render "devise/shared/error_messages" %>
    </div>
    
    <%= form_with url: questions_path, model: @question, local: true do |form| %>
      <div class="form-group d-flex flex-column">
        <%= form.label :title, "【質問】" %>
        <%= form.text_area :title, rows: 3,class: "form-control" %>
        </div>
      <div class="form-group d-flex flex-column">
        <%= form.label :detail, "【詳細】" %>
        <%= form.text_area :detail, rows: 5,class: "form-control"  %>
      </div>
      <div class="text-center">
        <%= form.submit "送信", class: "btn btn-primary btn-block btn-lg", data: {confirm: "新規投稿しますか？"} %>
      </div>
    <% end %>

    <section id="questions">
    <div class="container">
      <% @questions.each do |question| %>
        <div class="question-container">
         <a href="<%= "/questions/#{question.id}" %>">
          <div class="question">
            <div class="rowtitle">
              <div class="col-md-7">
                <div class="title-container">
                  <p class="questiontitle">
                    <%= question.title %>
                  </p>
                </div>
              </div>
                <div class="col-md-5">
                  <div class="info-text-right">
                  <p>質問日 <%= l question.updated_at, format: :long %></p>
                  <%= pluralize(question.reviews_count, "views", locale: :en) %>
                  </div>
                </div>
            </div>
          </div>

          </a>
        </div>
      <% end %>
    </div>
  </section>

app/views/questions/show.html.erb
<div id="container">
  <section id="question">
    <div class="title">
    <h3>【質問】</h3>
      <%= markdown(@question.title).html_safe %>
      <hr>
    </div>
    <div class="detail">
      <h3>【詳細】</h3>
      <%= markdown(@question.detail).html_safe %>
      <hr>
    </div>
    <div class="solution">
      <% @solutions.each.with_index(1) do |solution, i| %>
       <h3>【回答<%= i %>】</h3>
      <%= markdown(solution.detail).html_safe %>
      <% end %>
      
    </div>
    <div class= "detail">
     <div class="text-left">
      <h2>回答投稿</h2>
     </div>
     <%= form_with model:[@question,@solution], local: true do |form| %>
     <div class="form-group d-flex flex-column">
       <%= form.label :detail, "【回答】" %>
       <%= form.text_area :detail, rows: 5,class: "form-control"  %>
     </div>

      <div class="text-center">
        <%= form.submit "送信", class: "btn btn-primary btn-block btn-lg" %>
      </div>
     <% end %>
    </div>
  
  </section>
</div>

app/views/texts/index.html.erb
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" />

<div class="form-control-range">
<form class="mb-3 search-form mx-auto">
  <i class="fa fa-search search-icon" title="Search"></i>
  <input type="text" id="search-text" class="search-form search-text"
         placeholder="教材を探す" aria-label="Username" aria-describedby="search-form">
</form>
</div>

<div class="texts-wrapper">
    <div class="contents-title">
        <h2>テキスト教材</h2>
    </div>
</div>


<div class="row">
    <% @texts.each do |text| %>
        <div class="d-flex col-md-4 p-4" id="text">
          <div class = "container">
            <a href="/texts/<%= text.id %>" class="card">
                  <%= image_tag '/text.jpeg', class: 'card-img-top'%>
                <div class="card-body">
                    <h5 class="card-title">
                        <%= text.title %>
                    </h5>
                    <p class="card-text">
                        <%= text.genre %>
                    </p>
                </div>
            </a>
          </div>
        </div>
    <% end %>
</div>

app/views/texts/show.html.erb
<section id="text-contents">
    <h2><%= markdown(@text.title).html_safe %></h2>
    <p><%= markdown(@text.content).html_safe %></p>
</section>